import Head from 'next/head'

import Header from '@/component/header'
import Hero from '@/component/hero'
import Movie from '@/component/movies'


export default function Home() {
  return (
    <>
      <Head>
        <title>Онлайн Кинотеатр TVOЁ.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <Hero />
        <Movie category="New" />
        <Movie category="Watch" />
      </>
    </>
  )
}

